= Spring Boot showcase

This are steps to guide through a spring-boot application showcase. 

== RestController

[source, xml]
.dependencyManagement
----
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-dependencies</artifactId>
<version>1.2.1.RELEASE</version>
<type>pom</type>
<scope>import</scope>
----

[source, xml]
.dependency
----
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-web</artifactId>
----

[source, xml]
.build / plugins
----
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-maven-plugin</artifactId>
----


[source,java]
.App.java
----
@EnableAutoConfiguration
@RestController
@ComponentScan
public class App {

 @Autowired
 Dictionary dict;

 @RequestMapping("/{word}")
 public List<DictionaryWord> getTranslations(@PathVariable String word) 
 	throws IOException {
   return dict.getTranslations(word);
 }


 public static void main(String... args) {
   SpringApplication.run(App.class, args);
 }
}
----

<<<

== Adding actuator

[source, xml]
----
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-actuator</artifactId>
  <version>1.2.1.RELEASE</version>
</dependency>
----

<<<

== spring-data-jpa

Transaction Log and log endpoint

[source, xml]
.dependencies
----
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
  <groupId>org.hsqldb</groupId>
  <artifactId>hsqldb</artifactId>
  <scope>runtime</scope>
</dependency>
----

[source, java]
.TransactionLog.java
----
@Entity
public class TranslationLog {

	@Id @GeneratedValue
	private Long id;
	private String polishWord;
	private Integer cnt;
	private Date timestamp;

	//...
}
----

[source,java]
.TransactionLogRepository.java
----
public interface TransactionLogRepository extends JpaRepository<TranslationLog, Long> {

}
----

<<<

== REST & Spring Data REST

[source, java]
.App.java
----
@Autowired
TransactionLogRepository repository;

@RequestMapping("/log")
public List<TranslationLog> log() {
 return repository.findAll();
}

@RequestMapping("/{word}")
public List<DictionaryWord> getTranslations(@PathVariable String word) throws IOException {
 List<DictionaryWord> translations = dict.getTranslations(word);

 TranslationLog log = new TranslationLog();
 log.setPolishWord(word);
 log.setCnt(translations.size());
 log.setTimestamp(new Date());
 repository.save(log);

 return translations;
}
----

[source, xml]
.dependencies
----
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
----

[source, java]
----
@RepositoryRestResource(collectionResourceRel = "logs", path = "logs")
public interface TransactionLogRepository extends JpaRepository<TranslationLog, Long> {

}
----

<<<

== MySQL support

[source, xml]
.dependencies
----
<groupId>mysql</groupId>
<artifactId>mysql-connector-java</artifactId>
<version>5.1.31</version>
<scope>runtime</scope>
----

[source, yml]
.application.yml
----
spring:
	datasource:
		driverClassName: com.mysql.jdbc.Driver
		url: jdbc:mysql://localhost:3306/test
		username: root
		password: root
	jpa:
		generate-ddl: true
----

<<<

== Aspect

[source,xml]
----
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-aop</artifactId>
----

[source,java]
----
@Aspect
@Component
public class TranslationMonitor {

    @Autowired
    TransactionLogRepository repository;

    @Around("execution(* com.example.App.getTranslations(..))")
    public Object logTranslationAction(ProceedingJoinPoint joinPoint) throws Throwable {
        String word = (String) joinPoint.getArgs()[0];

        List<DictionaryWord> translations = (List<DictionaryWord>) joinPoint.proceed();

        TranslationLog log = new TranslationLog();
        log.setPolishWord(word);
        log.setCnt(translations.size());
        log.setTimestamp(new Date());
        repository.save(log);

        return translations;
    }

}

----